name: Lint
on:
  push:
    tags:
      - v*
    branches:
      - main
    paths-ignore:
      - "docs/**"
  pull_request:

jobs:
  lint:
    name: golangci-lint
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - uses: actions/setup-go@v4
        with:
          go-version-file: "go.mod"

      - name: Prepare .netrc
        uses: extractions/netrc@v1
        with:
          machine: github.com
          username: ${{ secrets.GO_MOD_USER }}
          password: ${{ secrets.GO_MOD_PASS }}

      - name: Lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.58
